### ISSUE TITLE
Multiple devices on the same network

### ISSUE THREAD

**Issue by sgeeurickx** [michaelarnauts/home-assistant-comfoconnect#10]
Hi,
Not really an issue, but I have an installation where there are 2 ComfoConnect LAN on the same network.  But it seems to be impossible to setup both of them in HA.
Do you think it would be lot of work to implement this feature ?

**Comment by michaelarnauts** [comment]
Do you have some log output? I only have one device, so I can't really test this.

**Comment by sgeeurickx** [comment]
With this new integration, I’m not able to connect to any of my ComfoConnect devices.  Same problem as others have reported.  I see my devices in the list, but then, after selecting one, I get « Unknown error occured ».  Where can I find logs ?

**Comment by Brewery-GIT** [comment]
> With this new integration, I’m not able to connect to any of my ComfoConnect devices. Same problem as others have reported. I see my devices in the list, but then, after selecting one, I get « Unknown error occured ». Where can I find logs ?

Yes I still have the issue. (Made an issue for this) I would be glad to submit logs, but which logs would I need to post?

**Comment by michaelarnauts** [comment]
> > Do you have some log output? I only have one device, so I can't really test this.
> 
> Not sure which logs to post. The values of sensors and the fan speed for entities of both integrations (172.8.50.16 and 17) give exactly the same values. Every x minutes when I open e.g. the fan speed for both entities, the values have changed to the other unit. (1 is at manual speed 1 and other at manual speed 3) So the integration is receiving data from both ComfoConnect LAN's, but it's not actually connecting to both simultaniously. I hope you have some clue where to look and/or which logs I need to post to help you out here...
> 
> thanks a lot!

This explanation helps! I'l not sure when I have time to look into this though. 

I think the issue is that I don't differentiate between the two instances.

**Comment by Wijnstra** [comment]
Thanks a lot in advance and be sure to receive my donation when you fix this :)

**Comment by michaelarnauts** [comment]
@Wijnstra @Brewery-GIT @sgeeurickx Could you try replacing the files in your `custom_components/comfoconnect` folder with the corresponding files from this ZIP? https://github.com/michaelarnauts/home-assistant-comfoconnect/archive/refs/heads/multiple-units.zip

**Comment by sgeeurickx** [comment]
I tried but as with the published version, when I want to add my devices, it shows both of them, but when I select one (or another), after a little time, I get "unknown error occured".

**Comment by Wijnstra** [comment]
@michaelarnauts  thanks a lot! 
The new code version works like a charm in my install. I can control my multiple Comfoconnect LAN's and all sensor data is correct now.

I'm sorry it doesn't work with you @sgeeurickx ; I think somethin else is wrong in your setup...

This change you should incorporate in the official module for sure :)

I'll buy you that coffee now @michaelarnauts

**Comment by sgeeurickx** [comment]
Don't know why but @Brewery-GIT had the same problem.  Previously, I was using the official integration (of course with only one device) and it worked.  I then just installed the new version via HACS, which should have discovered the previous config (but didn't).  Devices and HA are on the same subnet. I have no idea where I can find some useful logs.
I can add that with the latest code you sent, HA takes a while to start, taking a very long time starting ComfoConnect module.

**Comment by Wijnstra** [comment]
Did you try removing the config entry in configuration.yaml of the official integration? 

Are you able to connect to the Comfoconnect LAN with the phone app? Did you upgrade the firmware on Comfoconnect LAN? 

When I add the HACS integration, my devices were discovered and added just fine. At first both devices in HA gave the same values of sensors and fan setting visable was the same for both devices.. Only after the code update above, both of my devices were manageable correctly. 

I hope you get it to work :)

**Comment by sgeeurickx** [comment]
> Did you try removing the config entry in configuration.yaml of the official integration?
Yes I did
> Are you able to connect to the Comfoconnect LAN with the phone app? Did you upgrade the firmware on Comfoconnect LAN?
I can connect and I have version U1.2.6. I don't know how I can upgrade it.
> When I add the HACS integration, my devices were discovered and added just fine. At first both devices in HA gave the same values of sensors and fan setting visable was the same for both devices.. Only after the code update above, both of my devices were manageable correctly.
In my situation, HA didn't discover the devices but when I manually add them via the new integration, it suggests me both but then, unknown error occured when I select one of them.

**Comment by Wijnstra** [comment]
I have the same firmware, so that's not the problem.
Sorry, but no idea what is wrong...

**Comment by sgeeurickx** [comment]
![WhatsApp Image 2023-04-07 at 12 03 26](https://user-images.githubusercontent.com/76532283/230589929-4b66bae4-c782-4c70-8899-6452b52e1f29.jpeg)
That's my "connection status" screen

**Comment by sgeeurickx** [comment]
And I just tried to re-use the official integration and it works

**Comment by michaelarnauts** [comment]
For the unknown error, I really need logs to know what's going on.

I'll merge the branch for multiple devices as soon as I can (I'm sick right now), so it will work for all hacs installs.

I'm also almost ready to fix the reconnection bug when the unit gets unreachable.
