### ISSUE TITLE
No Ventilation Speed

### ISSUE THREAD

**Issue by MiJo112** [michaelarnauts/home-assistant-comfoconnect#28]
Unfortunately I can't see the possibility of changing the speed of the fans.
I would like to make it dependent on occupancy.
Do I have a config error?

<img width="242" alt="image" src="https://github.com/michaelarnauts/home-assistant-comfoconnect/assets/35043404/0e5c9e30-b76e-47fc-86af-11f9925a283e">

**Comment by michaelarnauts** [comment]
You have to click on the top row with the name ComfoAirQ. This will open a modal where you can change the speed.

**Comment by MiJo112** [comment]
omg I've tried everything for 30 minutes now....
Thanks ;)
