### ISSUE TITLE
any chance you can add the COMFOFOND-sensors?

### ISSUE THREAD

**Issue by pesmi30** [michaelarnauts/home-assistant-comfoconnect#38]
I have a ComfoAirQ system with a Comfofond attached.
That Comfofond has 4 sensors, that are present in the ComfoConnect:

SENSOR_COMFOFOND_TEMP_OUTDOOR = 416
SENSOR_COMFOFOND_TEMP_GROUND = 417
SENSOR_COMFOFOND_PERC_GHESTATE = 418
SENSOR_COMFOFOND_GHE_PRESENT = 419

A year ago I wrote my own Python program to report these sensors (along with the 'normal' ComfoAirQ sensors; so I know they are available)
I would love to have those comfofond-sensors available as 'HomeAssistant-sensors' (especially the first three),
I tried to 'fork' your integration to add them myself, but I am a poor programmer...

**Comment by pesmi30** [comment]
Thank you for you attention on this.
I *just* installed the new version (0.1.9) but I can't find the new sensors...

**Comment by michaelarnauts** [comment]
They are disabled by default, you should find them in the collapsed "not shown" entities section of the Diagnostic box on the ComfoAirQ device page.

![image](https://github.com/michaelarnauts/home-assistant-comfoconnect/assets/1193779/f355da2b-05b2-456d-a372-b1e079a8e1ce)

**Comment by pesmi30** [comment]
I must be stupid….
but can’t find

 

 



 



 



 

 



 



 

Van: Michaël Arnauts ***@***.***> 
Verzonden: dinsdag 2 april 2024 16:33
Aan: michaelarnauts/home-assistant-comfoconnect ***@***.***>
CC: pesmi30 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [michaelarnauts/home-assistant-comfoconnect] any chance you can add the COMFOFOND-sensors? (Issue #38)

 

They are disabled by default, you should find them in the collapsed "not shown" entities section of the Diagnostic box on the ComfoAirQ device page.

image.png (view on web) <https://github.com/michaelarnauts/home-assistant-comfoconnect/assets/1193779/f355da2b-05b2-456d-a372-b1e079a8e1ce>

**Comment by pesmi30** [comment]
After (yesterday) installing the latest version (0.1.10) I now have the new sensors available!
Thank you very much!
