### ISSUE TITLE
Failed to set up v.0.1.9

### ISSUE THREAD

**Issue by wgumaa** [michaelarnauts/home-assistant-comfoconnect#42]
Hi, having an issue setting up with the new version. 

From the logs I see a timeout. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 98, in connect
    self._reader, self._writer = await asyncio.wait_for(asyncio.open_connection(self.host, self.PORT), TIMEOUT)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by michaelarnauts** [comment]
0.1.9 was just a re-release of the same version, but with a version number (to make it easier to make beta versions later).

Based on your error, I would say your bridge is unavailable or doesn't respond.

**Comment by wgumaa** [comment]
Ok I will check the bridge when I get home later today

**Comment by wgumaa** [comment]
Working now after reconnecting comfoconnet.
