### ISSUE TITLE
Frozen sensors when disconnnected

### ISSUE THREAD

**Issue by tombartosz** [michaelarnauts/home-assistant-comfoconnect#5]
Feature request:
As a user I would like to have information if bridge is connected or not. 
Now if I disconnect power from ventilation unit all sensors shows last state in HA.
I have some automatons based on i.e temperature sensors (it provides input for central heating, also I'm using it when i want to check outside temperature) - so it gives false readings.
I would expect to have sensor that shows connnected (I'll use it in automations for "failover mode" ) or to make sensors "unavailable".

Best Regards,
Bartosz

P.S
This comfoconnect stuff is really good job. I'm using it since 2019 and it works quite reliable. Thanks.

**Comment by tombartosz** [comment]
I've just created such feature. Check my fork: https://github.com/tombartosz/home-assistant-comfoconnect

**Comment by michaelarnauts** [comment]
This change in the library allows us to properly detect an unreachable bridge: https://github.com/michaelarnauts/aiocomfoconnect/pull/5

There are still changes needed in this integration to mark sensors as unavailable though.
