### ISSUE TITLE
Integration with CAN bus

### ISSUE THREAD

**Issue by decontamin4t0R** [michaelarnauts/home-assistant-comfoconnect#55]
Hi,

currently, the library + this addon only supports updates via a LAN C bridge. However, most of the underlying CAN protocol should be known to be able to skip the bridge entirely. As I am migrating to HomeAssistant, I would be willing to invest some hours into making something less hacky than my current solution (https://github.com/decontamin4t0R/zcan). How would a possible extension look in your opinion?

Some points that I am having trouble unifying into my design:
- `aiocomfoconnect` already encapsulates a bit of the logic, however (in my case) be required to run on a different host than HomeAssistant
- I would prefer to use your already existing definitions for BinarySensors, etc. but am currently thinking about using mqtt to transmit the data (and thus probably skipping creating a whole addon and instead use mqtt discovery topics...)

For the start, I am thinking about forking this (the home-assistant) repo and commenting out a lot...

Thanks,
Max

**Comment by michaelarnauts** [comment]
Someone made a MQTT bridge with aiocomfoconnect.

This could be a useful base to start on? https://github.com/oysteing/comfoconnect-mqtt-bridge

**Comment by dan-s-github** [comment]
there are multiple variations using esphome and a esp32 
  
https://github.com/vekexasia/comfoair-esp32
https://github.com/felixstorm/esphome-custom-components/
https://github.com/yoziru/esphome-zehnder-comfoair
https://github.com/dan-s-github/zehnder-comfoair-can
