### ISSUE TITLE
Preset only displaying Auto

### ISSUE THREAD

**Issue by PrzemyslawKlys** [michaelarnauts/home-assistant-comfoconnect#67]
Hi, I've just installed the plugin and I'm pretty green when it comes to Home Assistant, but when I added it to dashboard it has only single preset which is Auto, and whenever I set any of those 4 bottom speeds, it throws an error that preset can't be changed. 

![image](https://github.com/user-attachments/assets/c54e5232-a19e-4fe7-afe3-1ef0114cc6c4)

Is there anything I can do, or it's more on plugin side?

**Comment by N3rdix** [comment]
What's the error you receive?

My 4 speed presets are working fine (but still on 0.1.12)

**Comment by PrzemyslawKlys** [comment]
Two things happen - when i switch from 1 to 2:

![image](https://github.com/user-attachments/assets/8ef0448a-03f8-432a-acb2-91461bd50098)

and then - auto switches to this sign

![image](https://github.com/user-attachments/assets/0f1c88e8-7ca6-46dc-b96f-4a7839cb8d53)

So clearly it looks like it's missing manual option that is used when i switch to different modes. 

![image](https://github.com/user-attachments/assets/d2063fee-8482-4e36-b5fc-699ef165d35d)

**Comment by PrzemyslawKlys** [comment]
You know what - it seems i was using Zehnder default configuration. Once I downloaded this plugin, everything seems to fixed itself. I am such a noob.
