### ISSUE TITLE
Please mention that version 0.2.3 needs HA 2024.9.x

### ISSUE THREAD

**Issue by N3rdix** [michaelarnauts/home-assistant-comfoconnect#84]
I just updated after reading the changelog and ran into those errors after restart. Could you please mention that this update requires a minimum HA version? I am still on 2024.8.3 and I would have postponed the update if I read it in the changelog 😄 

```
Logger: homeassistant.util.package
Quelle: util/package.py:123
Erstmals aufgetreten: 09:41:48 (3 Vorkommnisse)
Zuletzt protokolliert: 09:42:07

Unable to install package aiocomfoconnect==0.1.13: ERROR: Cannot install aiocomfoconnect==0.1.13 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by michaelarnauts** [comment]
Hmm, odd. It doesn't really need anything from 2024.9, so I don't see why it doesn't work.

Luckily, you can easily rollback to the older version.

**Comment by N3rdix** [comment]
That's what I did, just wanted to warn other users which might not be so technical.
For me it's fine for now until I update HA
