### ISSUE TITLE
Requirements for comfoconnect not found: ['aiocomfoconnect==0.1.13']. 

### ISSUE THREAD

**Issue by kroeckx** [michaelarnauts/home-assistant-comfoconnect#93]
After the upgrade of HA, I'm getting:
``Setup failed for custom integration 'comfoconnect': Requirements for comfoconnect not found: ['aiocomfoconnect==0.1.13'].``

``Unable to install package aiocomfoconnect==0.1.13: × No solution found when resolving dependencies: ╰─▶ Because aiocomfoconnect==0.1.13 depends on protobuf>=4.25.4,<5.0.0 and protobuf==5.28.3, we can conclude that aiocomfoconnect==0.1.13 cannot be used. And because you require aiocomfoconnect==0.1.13, we can conclude that your requirements are unsatisfiable.``

**Comment by jpdacostaza** [comment]
+1 seems to be due to : home-assistant:latest image (a1f238de239d)

**Comment by michaelarnauts** [comment]
And before posting this, have you checked that you have updated to the latest version of the integration?

**Comment by jpdacostaza** [comment]
> And before posting this, have you checked that you have updated to the latest version of the integration?

I agree feel like a dumbass did not check, appologies / thanks.

**Comment by kroeckx** [comment]
It did not offer an upgrade. I had to manually select a version to download.

**Comment by muraj238** [comment]
I have the same problem, how did you fix it, please? I updated from the second latest version to the 0.3.0
